@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request

Bob -> backendController: user Request
backendController -> backendService: Request

@enduml